name: Sell
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0, 3.0.1]
main: SellHand\Main
version: 2.0
author: Muqsit
authors: [KairusDarkSeeker & Zeao]
commands:
  sell:
    description: "Sells the item in your hand or all of your inventory's contents"
    permission: sell.command
permissions:
  sell:
    default: op
    children:
      sell.hand:
        default: op
      sell.all:
        default: op
      sell.command:
        default: true
